### ISSUE TITLE
Version 0.0.12 goes into an infinite cicle when generate samples

### ISSUE THREAD

**Issue by nmtsousa** [Vertafore/docular-ng-plugin#7]
I'm using docular and the latest update of docular-ng-plugin from 0.0.10 to 0.0.12 breaks the samples. The browser actually hangs running the angular.js script and I can see several hundreds of titles for the samples for the directive.

Forcing the project to use docular-ng-plugn 0.0.10 fixes the issue.

**Comment by stephenliberty** [comment]
Don't know how I missed that one. Reverted the bad commit that caused it.

**Comment by nmtsousa** [comment]
Checked with version 0.0.14 and it is working again.

Thank you!
